source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YapDatabaseObject-CloudKit_Example', :exclusive => true do
  pod "YapDatabaseObjectCloudKit", :path => "../"
end

target 'YapDatabaseObject-CloudKit_Tests', :exclusive => true do
  pod "YapDatabaseObjectCloudKit", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
